report_dict = {}
CALC_DETAILS =  "Calculation Details"


report_dict["1"] = {"title":"Current Estimated Credit Losses Summary","home_name":"Executive"}
report_dict["2"] = {"title":"CECL - Reserve Components","home_name":"Executive"}
report_dict["3"] = {"title":"Current Estimated Credit Losses by Period","home_name":"Executive"}
report_dict["4"] = {"title":"CECL - Unfunded Commitments","home_name":"Executive"}
report_dict["5"] = {"title":"Overview of CECL Methods Chosen for Financial Statements","home_name":"Summary"}
report_dict["6"] = {"title":"Graphical Overview of CECL Methods Chosen for Financial Statements","home_name":"Summary"}
report_dict["7"] = {"title":"Overview of CECL Results for Methods with Forward Cashflows","home_name":"Summary"}
report_dict["8"] = {"title":"Historical Maturity Terms","home_name":"Trends"}
report_dict["9"] = {"title":"Historical Interest Terms","home_name":"Trends"}
report_dict["10"] = {"title":"Historical Rate Types","home_name":"Trends"}
report_dict["11"] = {"title":"Current Estimated Credit Losses - Write-downs and Recoveries","home_name":"Footnotes"}
report_dict["12"] = {"title":"Current Estimated Credit Losses - Past Due Status","home_name":"Footnotes"}
report_dict["13"] = {"title":"Current Estimated Credit Losses - Non-Accrual Status","home_name":"Footnotes"}
report_dict["15"] = {"title":"Current Estimated Credit Losses - Loss Processing Parameters","home_name":"Configuration"}
report_dict["16"] = {"title":"Average Charge-Off Loss Rates, Net by Period Balances and Charge-Off Rates","home_name":CALC_DETAILS}
report_dict["17"] = {"title":"Average Charge-Off Loss Rate, Gross to Net Balances and Charge-Off Rates","home_name":CALC_DETAILS}
report_dict["18"] = {"title":"Average Charge-Off Final Loss Rates","home_name":CALC_DETAILS}
report_dict["19"] = {"title":"Average Charge-Off Estimated Loss Rates","home_name":CALC_DETAILS}
report_dict["20"] = {"title":"WARM Final Loss Rates","home_name":CALC_DETAILS}
report_dict["21"] = {"title":"WARM Estimated Loss Rates","home_name":CALC_DETAILS}
report_dict["22"] = {"title":"Migration Loss Rate - Gross Loss Rate Net by Period Results by Grade","home_name":CALC_DETAILS}
report_dict["23"] = {"title":"Migration Loss Rate - Gross Loss Rate by Net Recovery % Results by Grade","home_name":CALC_DETAILS}
report_dict["26"] = {"title":"Migration Final Loss Rate","home_name":CALC_DETAILS}
report_dict["27"] = {"title":"Migration Final Loss Rate - Total","home_name":CALC_DETAILS}
report_dict["28"] = {"title":"Migration Estimated Losses by Risk Rating","home_name":CALC_DETAILS}
report_dict["29"] = {"title":"Migration Estimated Losses by Risk Rating - Total","home_name":CALC_DETAILS}
report_dict["30"] = {"title":"PD Loss Rates by Grade","home_name":CALC_DETAILS}
report_dict["31"] = {"title":"LGD Loss Rates by Grade","home_name":CALC_DETAILS}
report_dict["32"] = {"title":"PD/LGD Loss Rate Results","home_name":CALC_DETAILS}
report_dict["33"] = {"title":"PD/LGD Final Loss Rate Results","home_name":CALC_DETAILS}
report_dict["34"] = {"title":"PD/LGD Estimated Losses by Risk Rating","home_name":CALC_DETAILS}
report_dict["35"] = {"title":"DCF Default Result by Grade","home_name":CALC_DETAILS}
report_dict["36"] = {"title":"DCF Recovery Rates Results by Grade","home_name":CALC_DETAILS}
report_dict["37"] = {"title":"DCF Final Loss Rate Results","home_name":CALC_DETAILS}
report_dict["38"] = {"title":"DCF Estimated Losses by Year by Risk Rating","home_name":CALC_DETAILS}
report_dict["39"] = {"title":"Closed Pool Loss Rate and Value Calculation","home_name":CALC_DETAILS}
report_dict["40"] = {"title":"Vintage Expected Loss Rate Calculation","home_name":CALC_DETAILS}
report_dict["41"] = {"title":"Historical Loss Rates by Risk Grade","home_name":CALC_DETAILS}
report_dict["42"] = {"title":"Analysis of Available Data","home_name":CALC_DETAILS}
report_dict["43"] = {"title":"Average Forward Balances","home_name":CALC_DETAILS}
report_dict["44"] = {"title":"Q Factor and Forward Look Moving Average Analysis","home_name":CALC_DETAILS}
report_dict["45"] = {"title":"Analysis of Historical Loss Rates and Economic Metrics","home_name":CALC_DETAILS}
report_dict["46"] = {"title":"WARM Basic Final Loss Rates","home_name":CALC_DETAILS}

#
# # report_dict = {}
# report_dict["6"] = {"title":"Graphical Overview of CECL Methods Chosen for Financial Statements","home_name":"Summary"}
# report_dict["7"] = {"title":"Overview of CECL Results for Methods with Forward Cashflows","home_name":"Summary"}
# report_dict["8"] = {"title":"Historical Maturity Terms","home_name":"Trends"}
# report_dict["9"] = {"title":"Historical Interest Terms","home_name":"Trends"}
# report_dict["10"] = {"title":"Historical Rate Types","home_name":"Trends"}
# report_dict["14"] = {"title":"Current Estimated Credit Losses - Historical Loss Processing Parameters","home_name":"Configuration"}
# report_dict["24"] = {"title":"Grade Migration Report","home_name":CALC_DETAILS}
# report_dict["25"] = {"title":"Grade Migration Report - Total","home_name":CALC_DETAILS}
